### PR TITLE
Increased code reuse and program robustness

### PR DESCRIPTION
**Pull request by BlackHole1**
1. Check if the first parameter is an array
2. Check whether the second parameter is a function
3. Avoid errors when the array has only one value

增强了代码的健壮性

1. 检测第一个参数是否为数组
2. 检测第二个参数是否为函数
3. 当数组只有一个参数时，避免了在for循环里的`array[i -1]`报错
4. 完善了test的测试向量

### CODE REVIEW

**Comment by BlackHole1** [comment]
tape的测试结果：

TAP version 13
# returns true for 1,2,3,4,5
ok 1 should be equal
# returns true for 1,1,3,4,5
ok 2 should be equal
# returns true for 1,1.5,3,4,5
ok 3 should be equal
# returns true for 1,2,3,4,6
ok 4 should be equal
# returns true for 5,4,3,1,1
ok 5 should be equal
# returns true for 5,4,3,2,1
ok 6 should be equal
# returns false for 1,5,2,3,4
ok 7 should be equal
# returns false for 5,4,3,1,2
ok 8 should be equal
# returns false for 12345
ok 9 should be equal
# returns true for 1
ok 10 should be equal
# returns true for 1,2,3,4,5
ok 11 should be equal
# returns false for 5,4,3,4,5
ok 12 should be equal

1..12
# tests 12
# pass  12

# ok

**Comment by BlackHole1** [comment]
tape的测试结果：

```
TAP version 13
# returns true for 1,2,3,4,5
ok 1 should be equal
# returns true for 1,1,3,4,5
ok 2 should be equal
# returns true for 1,1.5,3,4,5
ok 3 should be equal
# returns true for 1,2,3,4,6
ok 4 should be equal
# returns true for 5,4,3,1,1
ok 5 should be equal
# returns true for 5,4,3,2,1
ok 6 should be equal
# returns false for 1,5,2,3,4
ok 7 should be equal
# returns false for 5,4,3,1,2
ok 8 should be equal
# returns false for 12345
ok 9 should be equal
# returns true for 1
ok 10 should be equal
# returns true for 1,2,3,4,5
ok 11 should be equal
# returns false for 5,4,3,4,5
ok 12 should be equal

1..12
# tests 12
# pass  12

# ok
```

**Comment by BlackHole1** [comment]
推荐加入package-lock.json文件

**Review by dcousens — CHANGES_REQUESTED** [review]
I don't think this is our responsibility

**Comment by dcousens** [comment]
> Check if the first parameter is an array

the sane thing to do would be throw `TypeError` , not `return false`,  but, why restrict to `Array`?

> Check whether the second parameter is a function

throw `TypeError`,  or let it exploded as expected (natural errors are OK!)

> Avoid errors when the array has only one value

Please submit this as a different PR with a failing test case :+1:

**Pull request closed without merging**
