### PR TITLE
ues "TypeError" instead of "return"

### PR DESCRIPTION
**Pull request by BlackHole1**
I'm not familiar with "tape"，so i can't write  a failing test case. sorry

### CODE REVIEW

**Comment by dcousens** [comment]
I don't think this increases program robustness tbh.

The exceptions you've explicitly thrown would have thrown anyway... why bother?

**Comment by dcousens** [comment]
The fixtures I added in 0cd0cfc and a4b3c85 pass too,  so the `length < 1` is pointless

**Comment by BlackHole1** [comment]
ok..

**Comment by BlackHole1** [comment]
use `console` instead of "new throw"?

**Comment by dcousens** [comment]
@BlackHole1 tbh, I think leave it as is.

If `comparator` is not a function,  it will throw a native TypeError.
For example:
``` js
> 2()
TypeError: 2 is not a function
    at repl:1:2
```

If it isn't an `Array`... I suppose maybe we should throw incase `.length` is undefined...
Maybe only add that change.

**Comment by BlackHole1** [comment]
No No No...
because:
```
> "test123".length
7
```

**Comment by dcousens** [comment]
We could restrict it,  but,  "1234" would return `true` as is,  and "1243" return false... not the typical use case,  but,  it'd work haha.

**Comment by BlackHole1** [comment]
but，if is '123test'....  would  `return fasle`, because `3 - 't' => NaN`

**Comment by dcousens** [comment]
@BlackHole1 noted,  I now throw `TypeError` in def2e43,  released as `v1.0.5`

**Comment by BlackHole1** [comment]
yep. You're using `Array.isArray` to judge. And what about the `arguments` Object?

e.g.
```javascript
function a () {
  return Array.isArray(arguments)
}
a(1,2,3,4) // => false
```
because, arguments is link-array.

Can you consider supporting it?

**Comment by dcousens** [comment]
@BlackHole1 I don't think so...

We'd then need to check the last argument for the comparator function... etc.  Unnecessary complexity.

**Comment by dcousens** [comment]
You could trivially wrap it yourself if that is convenient:

``` js
function isSortedVA () {
  return isSorted.apply(null, arguments)
}
```

But,  if you wanted custom comparators... the complexity will increase considerably.

**Comment by BlackHole1** [comment]
yep, I didn't think about this method, thx

**Pull request closed without merging**
